void deformable_conv_forward_cuda(
    THCudaTensor * input,
    THCudaTensor * weight,
    THCudaTensor * offset,
    THCudaTensor * mask,
    THCudaTensor * output,
    THCudaTensor * columns,
    int kH,
    int kW,
    int strideH,
    int strideW,
    int padH,
    int padW,
    int dilationH,
    int dilationW,
    int deformable_group
);

void deformable_conv_backward_cuda(
    THCudaTensor * input,
    THCudaTensor * offset,
    THCudaTensor * mask,
    THCudaTensor * weight,
    THCudaTensor * columns,
    THCudaTensor * gradOutput,
    THCudaTensor * gradInput,
    THCudaTensor * gradOffset,
    THCudaTensor * gradMask,
    THCudaTensor * gradWeight,
    int kH,
    int kW,
    int strideH,
    int strideW,
    int padH,
    int padW,
    int dilationH,
    int dilationW,
    int deformable_group,
    float scale);
